# Makefile

# Compiler
CC = gcc

# Compiler Flags
CFLAGS = -Wall -Wextra -Werror

# Target executable
TARGET = game

# Source files
SRCS = game_logic.c input_validation.c

# Object files
OBJS = $(SRCS:.c=.o)

# Default rule
all: $(TARGET)

# Link object files to create executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

# Rule to compile .c files to .o files
%.o: %.c game.h
	$(CC) $(CFLAGS) -c $< -o $@

# Clean rule to remove object files and the executable
clean:
	rm -f $(OBJS)

# Fclean rule to remove all files generated by the build
fclean: clean
	rm -f $(TARGET)

# Rebuild the project
re: fclean all

.PHONY: all clean fclean re
